name: dliver
version: 1.0.3
author: Vostrikov Vitaliy <rasart.pro@gmail.com>
description: Package for worck with LiveReload extension
homepage: https://github.com/Rasarts/dliver
environment:
    sdk: ">=1.8.0 <2.0.0"
dependencies:
  watcher: "^0.9.7"
  yaml: "^2.1.7"
  cupid: "^0.9.9"
executables:
  dliver: dliver_cli
